name: End-to-end tests

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      tests:
        description: 'tests'
        type: string
        required: false
        default: ""

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Kong Manager
        run: |
          docker -v
          docker-compose -v
          docker ps -a
          docker-compose up -d
          docker ps -a

      - name: Run Cypresss tests
        uses: cypress-io/github-action@v6
        continue-on-error: true
        env:
          TESTS: ${{ inputs.tests }}

      - name: Archive Mochawesome report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: outputs

      - name: Shut Down Kong Manager
        run: |
          docker ps -a
          docker-compose down 
          docker ps -a